// Scan prescription
export const SCAN_PRESCRIPTION = "SCAN_PRESCRIPTION";
export const SCAN_IMAGE = "SCAN_IMAGE";
// User
export const SAGA_SIGNUP_USER = "SAGA_SIGNUP_USER";
export const SIGNUP_USER = "SIGNUP_USER";
export const SAGA_GET_CITIES = "SAGA_GET_CITIES";
export const GET_CITIES = "GET_CITIES";
export const SAGA_LOGIN_USER = "SAGA_LOGIN_USER";
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const SAGA_LOGOUT_USER = "SAGA_LOGOUT_USER";
export const SAGA_GET_PRESCRIPTION = "SAGA_GET_PRESCRIPTION";
export const GET_PRESCRIPTION = "GET_PRESCRIPTION";
export const SAGA_ADD_PRESCRIPTION = "SAGA_ADD_PRESCRIPTION";
export const ADD_PRESCRIPTION = "ADD_PRESCRIPTION";
export const SAGA_DELETE_PRESCRIPTIONS = "SAGA_DELETE_PRESCRIPTIONS";
export const DELETE_PRESCRIPTIONS = "DELETE_PRESCRIPTIONS";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const ADD_NOTIFICATION = "ADD_NOTIFICATION";
export const READ_NOTIFICATION = "READ_NOTIFICATION";
// Doctor
export const SAGA_GET_DOCTORS = "SAGA_GET_DOCTORS";
export const GET_DOCTORS = "GET_DOCTORS";
export const SAGA_SEARCH_DOCTORS = "SAGA_SEARCH_DOCTORS";
export const SEARCH_DOCTORS = "SEARCH_DOCTORS";
export const SAGA_GET_DOCTOR = "SAGA_GET_DOCTOR";
export const GET_DOCTOR = "GET_DOCTOR";
export const SAGA_GET_DOCTOR_APPOINTMENTS = "SAGA_GET_DOCTOR_APPOINTMENTS";
export const GET_DOCTOR_APPOINTMENTS = "GET_DOCTOR_APPOINTMENTS";
// Home
export const REQUEST_HOME_DATA = "REQUEST_HOME_DATA";
export const RECIEVE_HOME_DATA = "RECIEVE_HOME_DATA";
// Medications
export const REQUEST_MEDICATION = "REQUEST_MEDICATION";
export const RECIEVE_MEDICATION = "RECIEVE_MEDICATION";
export const REQUEST_MEDICATIONS = "REQUEST_MEDICATIONS";
export const RECIEVE_MEDICATIONS = "RECIEVE_MEDICATIONS";
export const SEARCH_MEDICATIONS = "SEARCH_MEDICATIONS";
export const RECIEVE_SEARCH_MEDICATIONS = "RECIEVE_SEARCH_MEDICATIONS";
export const SAGA_DELETE_FAVOURITE = "SAGA_DELETE_FAVOURITE";
export const DELETE_FAVOURITE = "DELETE_FAVOURITE";
export const ADD_FAVOURITE = "ADD_FAVOURITE";
export const SAGA_ADD_FAVOURITE = "SAGA_ADD_FAVOURITE";
export const GET_FAVOURITES = "GET_FAVOURITES";
export const SAGA_GET_FAVOURITES = "SAGA_GET_FAVOURITES";
export const SUBMIT_MEDICATION_ORDER = "SUBMIT_MEDICATION_ORDER";
export const SUBMIT_MEDICATION_ORDER_FAILED = "SUBMIT_MEDICATION_ORDER_FAILED";
export const REQUEST_ORDERS = "REQUEST_ORDERS";
export const RECIEVE_ORDERS = "RECIEVE_ORDERS";
// Appointments
export const REQUEST_APPOINTMENTS = "REQUEST_APPOINTMENTS";
export const RECIEVE_APPOINTMENTS = "RECIEVE_APPOINTMENTS";
export const BOOK_APPOINTMENT = "BOOK_APPOINTMENT";
export const BOOK_APPOINTMENT_RES = "BOOK_APPOINTMENT_RES";
