export const SCAN_PRESCRIPTION = "SCAN_PRESCRIPTION";
export const SCAN_IMAGE = "SCAN_IMAGE";

export const SAGA_SIGNUP_USER = "SAGA_SIGNUP_USER";
export const SIGNUP_USER = "SIGNUP_USER";
export const SAGA_GET_CITIES = "SAGA_GET_CITIES";
export const GET_CITIES = "GET_CITIES";
export const SAGA_LOGIN_USER = "SAGA_LOGIN_USER";
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const SAGA_LOGOUT_USER = "SAGA_LOGOUT_USER";

export const SAGA_GET_DOCTORS = "SAGA_GET_DOCTORS";
export const GET_DOCTORS = "GET_DOCTORS";
export const SAGA_SEARCH_DOCTORS = "SAGA_SEARCH_DOCTORS";
export const SEARCH_DOCTORS = "SEARCH_DOCTORS";
export const SAGA_GET_DOCTOR = "SAGA_GET_DOCTOR";
export const GET_DOCTOR = "GET_DOCTOR";
export const REQUEST_HOME_DATA = "REQUEST_HOME_DATA";
export const RECIEVE_HOME_DATA = "RECIEVE_HOME_DATA";

export const REQUEST_MEDICATIONS = "REQUEST_MEDICATIONS";
export const RECIEVE_MEDICATIONS = "RECIEVE_MEDICATIONS";
